#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export TERMINAL=gnome-terminal

if [[ -r ~/.aliasrc ]]; then
  . ~/.aliasrc
fi

if [[ -r ~/.functionsrc ]]; then
  . ~/.functionsrc
fi

if [[ -r ~/bin/global-auth-info.py ]]; then
  export TOKEN=$(~/bin/global-auth-info.py -e prod-us -v)
fi

if [[ -r ~/.zsh_nova ]]; then
  . ~/.zsh_nova
fi

if [[ -r /usr/share/virtualenvwrapper/virtualenvwrapper.sh ]]; then
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
fi

export SIGNUP_ENDPOINT=https://signup.api.rackspacecloud.com/v1
